# Generated by Django 2.2.7 on 2019-11-27 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='lat',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='lon',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL),
        ),
    ]
