# Generated by Django 2.2.7 on 2019-11-27 18:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0002_auto_20191127_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 27, 13, 54, 46, 459367)),
        ),
    ]
