# Generated by Django 2.2.7 on 2019-12-03 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
