# Generated by Django 2.2.7 on 2019-12-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0006_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='alt',
            field=models.TextField(default='', max_length=10),
        ),
    ]
