# Generated by Django 2.2.7 on 2019-12-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0007_bookmark_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='alt',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='lat',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='lon',
            field=models.TextField(),
        ),
    ]
